wsl = false
multigrid = true
vsync = true
maximized = false
srgb = true
idle = true
frame = "transparent"

[font]
size = 10.0

[[font.normal]]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraLight"

[[font.bold]]
family = "JetBrainsMono Nerd Font Mono"
style = "SemiBold"

[[font.italic]]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraLight Italic"

[font.features]
"JetBrainsMono Nerd Font Mono" = ["+zero"]
