color_bg="#161616"
color_fg="#dde1e6"
color_text="#262626"
color_comment="#525252"
color_date="#78a9ff"
color_time="#08bdba"
color_alert="#ee5396"
color_pomodoro="#ff7eb6"
color_session="#42be65"
color_window="#393939"
