color_bg="#f2f4f8"
color_fg="#161616"
color_text="#dde1e6"
color_comment="#525252"
color_date="#0f62fe"
color_time="#FF6F00"
color_alert="#ee5396"
color_pomodoro="#ff7eb6"
color_session="#42be65"
color_window="#dde1e6"
