format = """
$username\
$hostname\
$shlvl\
$singularity\
$kubernetes\
$directory\
$pijul_channel\
$docker_context\
$nix_shell\
$python\
$conda\
$meson\
$spack\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$hg_branch\
$nats\
$custom\
$sudo\
$line_break\
$jobs\
$status\
$container\
$character"""

# Replace the '❯' symbol in the prompt
[character]
success_symbol = '[󰌵 ](bold green)'
error_symbol = '[󰌶 ](bold red)'
vimcmd_symbol = '[󱈈 ](bold green)'
vimcmd_replace_one_symbol = '[󱈈 ](bold purple)'
vimcmd_replace_symbol = '[󱈈 ](bold purple)'
vimcmd_visual_symbol = '[󱈈 ](bold yellow)'

[username]
style_root = 'bold red'
style_user = 'bold green'
format = '[$user]($style) '

[hostname]
format = 'in [$hostname](bold bright-green): '
trim_at = '-'

[python]
format = '(via [$symbol $virtualenv]($style) )'
symbol = '󰆧'

[conda]
format = '(via [$symbol $environment]($style) )'
symbol = '󰆧'

[git_status]
format = '([\[$all_status$ahead_behind\]](bold) )'
conflicted = '[󱓌](red)'
ahead = '[](yellow)'
behind = '[](yellow)'
diverged = '[󱡷](red)'
up_to_date = '[✓](green)'
untracked = '[?](yellow)'
stashed = '[](purple)'
modified = '[](blue)'
staged = '[󰐕](green)'
renamed = '[→](blue)'
deleted = '[󰍴](red)'

[battery]
full_symbol = '󱊣 '
discharging_symbol = '󱊡 '
charging_symbol = '󰂄 '
