[colors]
ansi = [
  '#282828',
  '#be0f17',
  '#868715',
  '#cc881a',
  '#377375',
  '#a04b73',
  '#578e57',
  '#978771',
]
background = '#282828'
brights = [
  '#7f7061',
  '#f73028',
  '#aab01e',
  '#f7b125',
  '#719586',
  '#c77089',
  '#7db669',
  '#e6d4a3',
]
cursor_bg = '#e6d4a3'
cursor_border = '#e6d4a3'
cursor_fg = '#282828'
foreground = '#e6d4a3'
selection_bg = '#e6d4a3'
selection_fg = '#534a42'

[colors.indexed]

[metadata]
name = 'gruvbox-dark'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
