[colors]
ansi = [
  "#090618",
  "#c34043",
  "#76946a",
  "#c0a36e",
  "#7e9cd8",
  "#957fb8",
  "#6a9589",
  "#c8c093",
]
foreground = "#dcd7ba"
background = "#1f1f28"

brights = [
  "#727169",
  "#e82424",
  "#98bb6c",
  "#e6c384",
  "#7fb4ca",
  "#938aa9",
  "#7aa89f",
  "#dcd7ba",
]

cursor_bg = "#c8c093"
cursor_fg = "#c8c093"
cursor_border = "#c8c093"

selection_fg = "#c8c093"
selection_bg = "#2d4f67"

scrollbar_thumb = "#16161d"
split = "#16161d"

[colors.indexed]
16 = "#ffa066"
17 = "#ff5d62"

[colors.tab_bar]
background = '#090618'
inactive_tab_edge = '#1f1f28'
inactive_tab_edge_hover = '#1f1f28'

[colors.tab_bar.active_tab]
bg_color = '#1f1f28'
fg_color = '#dcd7ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#2d4f67'
fg_color = '#dcd7ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#090618'
fg_color = '#dcd7ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#090618'
fg_color = '#dcd7ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#2d4f67'
fg_color = '#dcd7ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'
