[colors]
ansi = [
  '#000000',
  '#e06c75',
  '#98c379',
  '#d19a66',
  '#61afef',
  '#c678dd',
  '#56b6c2',
  '#abb2bf',
]
background = '#282c34'
brights = [
  '#5c6370',
  '#e06c75',
  '#98c379',
  '#d19a66',
  '#61afef',
  '#c678dd',
  '#56b6c2',
  '#fffefe',
]

cursor_bg = '#7d899f'
cursor_border = '#a5b0c5'
cursor_fg = '#000000'
foreground = '#a5b0c5'

[colors.indexed]

[metadata]
name = 'onedark-dark'
origin_url = 'https://github.com/Gogh-Co/Gogh'
