#!/usr/bin/env bash
# vim: ai:ts=4:sw=4:noet
# Dynamically change your colorscheme

declare -A SUPPORTED=(
	["ayu"]="dark light mirage"
	["catppuccin"]="darker dark dimmed light"
	["dracula"]=""
	["github"]="dark dimmed light"
	["gotham"]=""
	["gruvbox"]="dark light"
	["nord"]=""
	["nightowl"]=""
	["onedark"]=""
	["palenight"]=""
	["rosepine"]="dark dimmed light"
	["solarized"]="dark light"
	["tokyonight"]="dark dimmed light"
)

function in_array {
	IFS=' ' read -ra array <<< $2

	if [[ ${#array[@]} = 0 && "$1" = "" ]]
	then
		return 1
	fi

	if [[ ( ${#array[@]} == 0 && "$1" != "" ) ||
		( ${#array[@]} != 0 && "$1" == "" ) ]]
	then
		return 0
	fi

	for e in ${array[*]}
	do
		if [[ "$e" == "$1" ]]
		then
			return 1
		fi
	done

	return 0
}

function print_help {
    echo "You must provide a colorscheme as an argument to the script."
    echo "You can additionally provide variants of that colorscheme as a second argument."
    echo "Note that flags must precede the colorscheme name."
    echo ""
    echo "The supported colorschemes are:"
	for elem in "${!SUPPORTED[@]}"
    do
        echo -n "  $elem"
		IFS=' ' read -ra variants <<< "${SUPPORTED[${elem}]}"
		if [ ${#variants[@]} != 0 ]
		then
			echo -n " [ "
			for v in "${variants[@]}"
			do
				echo -n "${v} "
			done
			echo -n "]"
		fi
		echo ""
    done
    echo ""
    echo "Example: \"color onedark\" or \"color ayu mirage\"."
}

function reload_nvim_plugins {
	nvim-ctrl 'source ~/.config/nvim/lua/plugins/configs/feline/init.lua'
	nvim-ctrl 'source ~/.config/nvim/lua/plugins/configs/bufferline/init.lua'
	for folder in ~/.config/nvim/lua/plugins/configs/colorschemes/*
	do
		nvim-ctrl 'source '"$folder"'/init.lua'
	done
}

while getopts 'h' flag; do
    case "${flag}" in
        h) print_help
           exit 0 ;;
        *) print_help
           exit 1 ;;
    esac
done
shift $(( OPTIND - 1 ))

color=$1
variant=$2

# Checks
if [ "$1" == "" ];
then
    echo "ERROR: You need to specify a color."
	echo "Use \"color -h\" for help."
    exit 1
fi

if [[ -v "$SUPPORTED[${color}]" ]];
then
    echo "ERROR: The proposed color is not currently supported."
	echo "Use \"color -h\" for help."
    exit 1
fi

IFS=' ' read -ra variants <<< "${SUPPORTED[$color]}"
if in_array "$variant" "${variants[*]}"
then
    echo "ERROR: You need to specify a valid variant for the chosen color."
	echo "Use \"color -h\" for help."
    exit 1
fi

# Neovim
if [ "$color" == "github" ]
then
	if [ "$variant" == "dark" ]
	then
		sed -i '' 's/colors_name\ =\ ".*"/colors_name\ =\ \"github_dark_default\"/g' ~/.config/nvim/lua/colors.lua
	elif [ "$variant" == "dimmed" ]
	then
		sed -i '' 's/colors_name\ =\ ".*"/colors_name\ =\ \"github_dimmed\"/g' ~/.config/nvim/lua/colors.lua
	elif [ "$variant" == "light" ]
	then
		sed -i '' 's/colors_name\ =\ ".*"/colors_name\ =\ \"github_light_default\"/g' ~/.config/nvim/lua/colors.lua
	fi
elif [ "$color" == "rosepine" ]
then
	sed -i '' 's/colors_name\ =\ ".*"/colors_name\ =\ \"rose-pine\"/g' ~/.config/nvim/lua/colors.lua
elif [ "$color" == "nightowl" ]
then
	sed -i '' 's/colors_name\ =\ ".*"/colors_name\ =\ \"night-owl\"/g' ~/.config/nvim/lua/colors.lua
else
	sed -i '' 's/colors_name\ =\ ".*"/colors_name\ =\ "'"$color"'"/g' ~/.config/nvim/lua/colors.lua
fi

if [ "$variant" != "" ]
then
    if [ "$color" == "ayu" ]
    then
        if [ "$variant" == "mirage" ]
        then
            sed -i '' "s/mirage\ =\ .*,/mirage\ =\ true,/g" ~/.config/nvim/lua/plugins/configs/colorschemes/ayu/init.lua
			sed -i '' 's/set\ background=.*")/set\ background=dark")/g' ~/.config/nvim/lua/colors.lua
        else
            sed -i '' "s/mirage\ =\ .*,/mirage\ =\ false,/g" ~/.config/nvim/lua/plugins/configs/colorschemes/ayu/init.lua
			sed -i '' 's/set\ background=.*")/set\ background='"$variant"'")/g' ~/.config/nvim/lua/colors.lua
        fi
	elif [ "$color" == "catppuccin" ]
	then
		if [ "$variant" == "darker" ]
		then
			sed -i '' "s/catppuccin_flavour\ =\ \".*\"/catppuccin_flavour\ =\ \"mocha\"/g" ~/.config/nvim/lua/colors.lua
		elif [ "$variant" == "dark" ]
		then
			sed -i '' "s/catppuccin_flavour\ =\ \".*\"/catppuccin_flavour\ =\ \"macchiato\"/g" ~/.config/nvim/lua/colors.lua
		elif [ "$variant" == "dimmed" ]
		then
			sed -i '' "s/catppuccin_flavour\ =\ \".*\"/catppuccin_flavour\ =\ \"frappe\"/g" ~/.config/nvim/lua/colors.lua
		elif [ "$variant" == "light" ]
		then
			sed -i '' "s/catppuccin_flavour\ =\ \".*\"/catppuccin_flavour\ =\ \"latte\"/g" ~/.config/nvim/lua/colors.lua
		fi
	elif [ "$color" == "rosepine" ]
	then
		if [ "$variant" == "dimmed" ]
		then
			sed -i '' "s/dark_variant\ =\ \".*\"/dark_variant\ =\ \"moon\"/g" ~/.config/nvim/lua/plugins/configs/colorschemes/rose-pine/init.lua
			sed -i '' 's/set\ background=.*")/set\ background=dark")/g' ~/.config/nvim/lua/colors.lua
		else
			sed -i '' "s/dark_variant\ =\ \".*\"/dark_variant\ =\ \"main\"/g" ~/.config/nvim/lua/plugins/configs/colorschemes/rose-pine/init.lua
			sed -i '' 's/set\ background=.*")/set\ background='"$variant"'")/g' ~/.config/nvim/lua/colors.lua
		fi
	elif [ "$color" == "tokyonight" ]
	then
		if [ "$variant" == "dark" ]
		then
			sed -i '' "s/tokyonight_style\ =\ \".*\"/tokyonight_style\ =\ \"night\"/g" ~/.config/nvim/lua/colors.lua
		elif [ "$variant" == "dimmed" ]
		then
			sed -i '' "s/tokyonight_style\ =\ \".*\"/tokyonight_style\ =\ \"storm\"/g" ~/.config/nvim/lua/colors.lua
		elif [ "$variant" == "light" ]
		then
			sed -i '' "s/tokyonight_style\ =\ \".*\"/tokyonight_style\ =\ \"day\"/g" ~/.config/nvim/lua/colors.lua
		fi
	else
		if [ "$variant" == "light" ]
		then
			sed -i '' 's/set\ background=.*")/set\ background=light")/g' ~/.config/nvim/lua/colors.lua
		else
			sed -i '' 's/set\ background=.*")/set\ background=dark")/g' ~/.config/nvim/lua/colors.lua
		fi
	fi
else
    sed -i '' 's/set\ background=.*")/set\ background=dark")/g' ~/.config/nvim/lua/colors.lua
fi
reload_nvim_plugins
nvim-ctrl 'source ~/.config/nvim/lua/colors.lua'
reload_nvim_plugins
nvim-ctrl 'syntax on'

# alacritty
if [ "$variant" != "" ]
then
    sed -i '' 's/colors:\ \*.*/colors:\ \*'"$color"'-'"$variant"'/g' ~/.config/alacritty/alacritty.yml
else
    sed -i '' 's/colors:\ \*.*/colors:\ \*'"$color"'/g' ~/.config/alacritty/alacritty.yml
fi

# kitty
if [ "$variant" != "" ]
then
	sed -i '' 's/include\ colorschemes.*/include\ colorschemes\/'"$color"'-'"$variant"'.conf/g' ~/.config/kitty/kitty.conf
else
	sed -i '' 's/include\ colorschemes.*/include\ colorschemes\/'"$color"'.conf/g' ~/.config/kitty/kitty.conf
fi
killall -SIGUSR1 kitty

# wezterm
if [ "$variant" != "" ]
then
	sed -i '' 's/color_scheme\ =.*/color_scheme\ =\ "'"$color"'-'"$variant"'",/g' ~/.config/wezterm/wezterm.lua
else
	sed -i '' 's/color_scheme\ =.*/color_scheme\ =\ "'"$color"'",/g' ~/.config/wezterm/wezterm.lua
fi

# tmux
if [ "$variant" != "" ]
then
	sed -i '' 's/source-file.*colorschemes.*/source-file\ \~\/\.config\/tmux\/colorschemes\/'"$color"''"-$variant"'\.tmux\.conf/g' ~/.config/tmux/tmux.conf
else
	sed -i '' 's/source-file.*colorschemes.*/source-file\ \~\/\.config\/tmux\/colorschemes\/'"$color"'\.tmux\.conf/g' ~/.config/tmux/tmux.conf
fi
tmux source-file ~/.tmux.conf
tmux source-file ~/.tmux.conf

exit 0
